import csv
import io
from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session
from app.database.database import SessionLocal
from app.database.models import Call, Caller, CallSummary, ActionItem

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

router = APIRouter(prefix="/export", tags=["Executive Export"])

@router.get("/calls/csv")
def export_calls_csv(mode: str = None, db: Session = Depends(get_db)):
    """
    Exports calls as a formatted CSV spreadsheet.
    """
    query = db.query(Call).order_by(Call.started_at.desc())
    if mode and mode != "all":
        query = query.filter(Call.mode == mode)
    calls = query.all()

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Call ID", "Date/Time", "Desk Persona", "Language", "Caller Name", "Caller Phone",
        "Category", "Urgency", "Summary", "Action Required", "Timeline", "Meeting Detected", "Spam Screened"
    ])

    for c in calls:
        s = c.summary
        caller = c.caller
        writer.writerow([
            c.id,
            c.started_at.strftime("%Y-%m-%d %H:%M") if c.started_at else "",
            c.mode or "Student",
            getattr(c, "language", "English") or "English",
            caller.name if caller else "Unknown",
            caller.phone if caller else "",
            c.call_type or "General Inquiry",
            s.urgency if s else "medium",
            s.summary if s else "",
            s.action_required if s else "",
            s.suggested_follow_up if s else "",
            "Yes" if (s and s.meeting_detected) else "No",
            "Yes" if getattr(c, "is_spam", False) else "No"
        ])

    csv_data = output.getvalue()
    return Response(
        content=csv_data,
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=kira_call_dossier.csv"}
    )

@router.get("/calls/{call_id}/markdown")
def export_call_markdown(call_id: int, db: Session = Depends(get_db)):
    """
    Generates a Notion/Obsidian compatible executive markdown brief.
    """
    call = db.query(Call).filter(Call.id == call_id).first()
    if not call:
        raise HTTPException(status_code=404, detail="Call not found")

    s = call.summary
    caller = call.caller

    md = f"""# 📞 Call Dossier: {caller.name if caller else 'Unknown Caller'}
- **Desk Persona**: {call.mode or 'Student'}
- **Date/Time**: {call.started_at.strftime('%A, %B %d, %Y at %I:%M %p') if call.started_at else 'Recent'}
- **Caller Contact**: {caller.phone if caller else 'N/A'} {f'• {caller.email}' if caller and caller.email else ''}
- **Category**: `{call.call_type or 'General Inquiry'}`
- **Urgency Level**: `{'🔴 High' if s and s.urgency == 'high' else '🟡 Medium' if s and s.urgency == 'medium' else '🟢 Low'}`

## 📋 Executive Summary
{s.summary if s else 'Call in progress or summary pending.'}

## ⚡ Key Details & Requests
"""
    if s and s.key_points:
        import json
        try:
            pts = json.loads(s.key_points) if isinstance(s.key_points, str) else s.key_points
            for p in pts:
                md += f"- {p}\n"
        except Exception:
            md += f"- {s.key_points}\n"
    else:
        md += "- No extra details recorded.\n"

    md += f"""
## 📌 Next Action Directive
**{s.action_required if s and s.action_required else 'None'}** (Target: `{s.suggested_follow_up if s and s.suggested_follow_up else 'This week'}`)

---
*Generated by KIRA Autonomous Communication Agent for Keerthana.*
"""
    return {"call_id": call_id, "markdown": md}
